### ISSUE TITLE
Colcon build failed

### ISSUE THREAD

**Issue by feliperad** [open-rmf/rmf_demos#217]
I'm at Ubuntu 22.04, with ROS humble;

error message

Starting >>> rmf_demos_dashboard_resources
Starting >>> rmf_demos_assets
Starting >>> rmf_demos_fleet_adapter
Starting >>> rmf_demos_maps                                                  
Starting >>> rmf_demos_tasks
Starting >>> rmf_demos_bridges                                               
Finished <<< rmf_demos_assets [3.12s]                                                                                                                   
Finished <<< rmf_demos_dashboard_resources [3.24s]                                                                                                      
Starting >>> rmf_demos_panel
--- stderr: rmf_demos_maps                                                                                                                                   
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_generator", line 33, in <module>
    sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_generator')())
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map_generator/building_map_generator.py", line 24, in main
    g.generate_ignition_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 72, in generate_ignition_sdf
    self.generate_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 41, in generate_sdf
    building.generate_sdf_models(output_models_dir)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 537, in generate_sdf_models
    level.generate_sdf_model(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 358, in generate_sdf_model
    self.write_sdf(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 343, in write_sdf
    self.generate_floors(model_ele, model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 317, in generate_floors
    floor.generate(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 231, in generate
    self.triangulate_polygon(self.polygon, triangles)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 144, in triangulate_polygon
    for item in geom:
TypeError: 'GeometryCollection' object is not iterable
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_generator", line 33, in <module>
    sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_generator')())
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map_generator/building_map_generator.py", line 16, in main
    g.generate_gazebo_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 59, in generate_gazebo_sdf
    self.generate_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 41, in generate_sdf
    building.generate_sdf_models(output_models_dir)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 537, in generate_sdf_models
    level.generate_sdf_model(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 358, in generate_sdf_model
    self.write_sdf(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 343, in write_sdf
    self.generate_floors(model_ele, model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 317, in generate_floors
    floor.generate(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 231, in generate
    self.triangulate_polygon(self.polygon, triangles)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 144, in triangulate_polygon
    for item in geom:
TypeError: 'GeometryCollection' object is not iterable
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_generator", line 33, in <module>
    sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_generator')())
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map_generator/building_map_generator.py", line 16, in main
    g.generate_gazebo_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 59, in generate_gazebo_sdf
    self.generate_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 41, in generate_sdf
    building.generate_sdf_models(output_models_dir)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 537, in generate_sdf_models
    level.generate_sdf_model(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 358, in generate_sdf_model
    self.write_sdf(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 343, in write_sdf
    self.generate_floors(model_ele, model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 317, in generate_floors
    floor.generate(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 231, in generate
    self.triangulate_polygon(self.polygon, triangles)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 144, in triangulate_polygon
    for item in geom:
TypeError: 'GeometryCollection' object is not iterable
gmake[2]: *** [CMakeFiles/generate_battle_royale_crowdsim_ign.dir/build.make:77: maps/battle_royale_ign/battle_royale.world] Erro 1
gmake[1]: *** [CMakeFiles/Makefile2:281: CMakeFiles/generate_battle_royale_crowdsim_ign.dir/all] Erro 2
gmake[1]: ** Esperando que outros processos terminem.
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_generator", line 33, in <module>
    sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_generator')())
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map_generator/building_map_generator.py", line 24, in main
    g.generate_ignition_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 72, in generate_ignition_sdf
    self.generate_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 41, in generate_sdf
    building.generate_sdf_models(output_models_dir)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 537, in generate_sdf_models
    level.generate_sdf_model(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 358, in generate_sdf_model
    self.write_sdf(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 343, in write_sdf
    self.generate_floors(model_ele, model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 317, in generate_floors
    floor.generate(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 231, in generate
    self.triangulate_polygon(self.polygon, triangles)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 144, in triangulate_polygon
    for item in geom:
TypeError: 'GeometryCollection' object is not iterable
gmake[2]: *** [CMakeFiles/generate_battle_royale_crowdsim.dir/build.make:77: maps/battle_royale/battle_royale.world] Erro 1
gmake[1]: *** [CMakeFiles/Makefile2:255: CMakeFiles/generate_battle_royale_crowdsim.dir/all] Erro 2
gmake[2]: *** [CMakeFiles/generate_office_crowdsim.dir/build.make:77: maps/office/office.world] Erro 1
gmake[1]: *** [CMakeFiles/Makefile2:567: CMakeFiles/generate_office_crowdsim.dir/all] Erro 2
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_generator", line 33, in <module>
    sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_generator')())
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map_generator/building_map_generator.py", line 16, in main
    g.generate_gazebo_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 59, in generate_gazebo_sdf
    self.generate_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 41, in generate_sdf
    building.generate_sdf_models(output_models_dir)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 537, in generate_sdf_models
    level.generate_sdf_model(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 358, in generate_sdf_model
    self.write_sdf(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 343, in write_sdf
    self.generate_floors(model_ele, model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 317, in generate_floors
    floor.generate(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 231, in generate
    self.triangulate_polygon(self.polygon, triangles)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 144, in triangulate_polygon
    for item in geom:
TypeError: 'GeometryCollection' object is not iterable
gmake[2]: *** [CMakeFiles/generate_hotel_crowdsim_ign.dir/build.make:77: maps/hotel_ign/hotel.world] Erro 1
gmake[1]: *** [CMakeFiles/Makefile2:515: CMakeFiles/generate_hotel_crowdsim_ign.dir/all] Erro 2
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_generator", line 33, in <module>
    sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_generator')())
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map_generator/building_map_generator.py", line 16, in main
    g.generate_gazebo_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 59, in generate_gazebo_sdf
    self.generate_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 41, in generate_sdf
    building.generate_sdf_models(output_models_dir)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 537, in generate_sdf_models
    level.generate_sdf_model(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 358, in generate_sdf_model
    self.write_sdf(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 343, in write_sdf
    self.generate_floors(model_ele, model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 317, in generate_floors
    floor.generate(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 231, in generate
    self.triangulate_polygon(self.polygon, triangles)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 144, in triangulate_polygon
    for item in geom:
TypeError: 'GeometryCollection' object is not iterable
gmake[2]: *** [CMakeFiles/generate_hotel_crowdsim.dir/build.make:77: maps/hotel/hotel.world] Erro 1
gmake[1]: *** [CMakeFiles/Makefile2:489: CMakeFiles/generate_hotel_crowdsim.dir/all] Erro 2
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_generator", line 33, in <module>
    sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_generator')())
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map_generator/building_map_generator.py", line 16, in main
    g.generate_gazebo_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 59, in generate_gazebo_sdf
    self.generate_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 41, in generate_sdf
    building.generate_sdf_models(output_models_dir)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 537, in generate_sdf_models
    level.generate_sdf_model(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 358, in generate_sdf_model
    self.write_sdf(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 343, in write_sdf
    self.generate_floors(model_ele, model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 317, in generate_floors
    floor.generate(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 231, in generate
    self.triangulate_polygon(self.polygon, triangles)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 144, in triangulate_polygon
    for item in geom:
TypeError: 'GeometryCollection' object is not iterable
gmake[2]: *** [CMakeFiles/generate_airport_terminal_crowdsim.dir/build.make:77: maps/airport_terminal/airport_terminal.world] Erro 1
gmake[1]: *** [CMakeFiles/Makefile2:177: CMakeFiles/generate_airport_terminal_crowdsim.dir/all] Erro 2
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_generator", line 33, in <module>
    sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_generator')())
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map_generator/building_map_generator.py", line 24, in main
    g.generate_ignition_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 72, in generate_ignition_sdf
    self.generate_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 41, in generate_sdf
    building.generate_sdf_models(output_models_dir)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 537, in generate_sdf_models
    level.generate_sdf_model(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 358, in generate_sdf_model
    self.write_sdf(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 343, in write_sdf
    self.generate_floors(model_ele, model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 317, in generate_floors
    floor.generate(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 231, in generate
    self.triangulate_polygon(self.polygon, triangles)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 144, in triangulate_polygon
    for item in geom:
TypeError: 'GeometryCollection' object is not iterable
gmake[2]: *** [CMakeFiles/generate_clinic_crowdsim.dir/build.make:77: maps/clinic/clinic.world] Erro 1
gmake[1]: *** [CMakeFiles/Makefile2:411: CMakeFiles/generate_clinic_crowdsim.dir/all] Erro 2
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_generator", line 33, in <module>
    sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_generator')())
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map_generator/building_map_generator.py", line 24, in main
    g.generate_ignition_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 72, in generate_ignition_sdf
    self.generate_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 41, in generate_sdf
    building.generate_sdf_models(output_models_dir)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 537, in generate_sdf_models
    level.generate_sdf_model(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 358, in generate_sdf_model
    self.write_sdf(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 343, in write_sdf
    self.generate_floors(model_ele, model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 317, in generate_floors
    floor.generate(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 231, in generate
    self.triangulate_polygon(self.polygon, triangles)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 144, in triangulate_polygon
    for item in geom:
TypeError: 'GeometryCollection' object is not iterable
gmake[2]: *** [CMakeFiles/generate_airport_terminal_crowdsim_ign.dir/build.make:77: maps/airport_terminal_ign/airport_terminal.world] Erro 1
gmake[1]: *** [CMakeFiles/Makefile2:203: CMakeFiles/generate_airport_terminal_crowdsim_ign.dir/all] Erro 2
gmake[2]: *** [CMakeFiles/generate_clinic_crowdsim_ign.dir/build.make:77: maps/clinic_ign/clinic.world] Erro 1
gmake[1]: *** [CMakeFiles/Makefile2:437: CMakeFiles/generate_clinic_crowdsim_ign.dir/all] Erro 2
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rmf_building_map_tools/building_map_generator", line 33, in <module>
    sys.exit(load_entry_point('rmf-building-map-tools==1.6.2', 'console_scripts', 'building_map_generator')())
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map_generator/building_map_generator.py", line 24, in main
    g.generate_ignition_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 72, in generate_ignition_sdf
    self.generate_sdf(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/generator.py", line 41, in generate_sdf
    building.generate_sdf_models(output_models_dir)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/building.py", line 537, in generate_sdf_models
    level.generate_sdf_model(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 358, in generate_sdf_model
    self.write_sdf(model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 343, in write_sdf
    self.generate_floors(model_ele, model_name, model_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/level.py", line 317, in generate_floors
    floor.generate(
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 231, in generate
    self.triangulate_polygon(self.polygon, triangles)
  File "/opt/ros/humble/lib/python3.10/site-packages/building_map/floor.py", line 144, in triangulate_polygon
    for item in geom:
TypeError: 'GeometryCollection' object is not iterable
gmake[2]: *** [CMakeFiles/generate_office_crowdsim_ign.dir/build.make:77: maps/office_ign/office.world] Erro 1
gmake[1]: *** [CMakeFiles/Makefile2:593: CMakeFiles/generate_office_crowdsim_ign.dir/all] Erro 2
gmake: *** [Makefile:146: all] Erro 2

Failed   <<< rmf_demos_maps [3.47s, exited with code 2]
Aborted  <<< rmf_demos_panel [0.35s]
Aborted  <<< rmf_demos_fleet_adapter [3.68s]                                                                                      
Aborted  <<< rmf_demos_bridges [3.54s]
Aborted  <<< rmf_demos_tasks [3.59s]

Summary: 2 packages finished [4.80s]
  1 package failed: rmf_demos_maps
  4 packages aborted: rmf_demos_bridges rmf_demos_fleet_adapter rmf_demos_panel rmf_demos_tasks
  4 packages had stderr output: rmf_demos_bridges rmf_demos_fleet_adapter rmf_demos_maps rmf_demos_tasks
  3 packages not processed

**Comment by Yadunund** [comment]
Can you provide more information
- Whether ROS humble was installed via binaries or source build
- Whether Open-RMF was installed via binaries and source build
- Instructions to reproduce  the build error. ie steps on how you created the workspace, what you sourced, and what build  was command used

Also in the future, please create a [gist](https://gist.github.com/) for your terminal output if its long. It greatly improves readability of this ticket.

**Comment by feliperad** [comment]
> Can you provide more information
> 
> * Whether ROS humble was installed via binaries or source build
> * Whether Open-RMF was installed via binaries and source build
> * Instructions to reproduce  the build error. ie steps on how you created the workspace, what you sourced, and what build  was command used
> 
> Also in the future, please create a [gist](https://gist.github.com/) for your terminal output if its long. It greatly improves readability of this ticket.

I'm sorry; both ROS humble and OpenRMF were installed via binaries

**Comment by harunkurtdev** [comment]
```bash
--- stderr: rmf_demos_maps                                             
BUILDING WORLDFILE WITH COMMAND: ros2 run rmf_building_map_tools building_map_generator gazebo /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/airport_terminal/airport_terminal.building.yaml /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/airport_terminal/airport_terminal.world /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/airport_terminal/models
DOWNLOADING MODELS WITH COMMAND: ros2 run rmf_building_map_tools building_map_model_downloader /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/airport_terminal/airport_terminal.building.yaml
BUILDING WORLDFILE WITH COMMAND: ros2 run rmf_building_map_tools building_map_generator gazebo /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/battle_royale/battle_royale.building.yaml /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/battle_royale/battle_royale.world /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/battle_royale/models
DOWNLOADING MODELS WITH COMMAND: ros2 run rmf_building_map_tools building_map_model_downloader /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/battle_royale/battle_royale.building.yaml
BUILDING WORLDFILE WITH COMMAND: ros2 run rmf_building_map_tools building_map_generator gazebo /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/campus/campus.building.yaml /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/campus/campus.world /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/campus/models
DOWNLOADING MODELS WITH COMMAND: ros2 run rmf_building_map_tools building_map_model_downloader /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/campus/campus.building.yaml
BUILDING WORLDFILE WITH COMMAND: ros2 run rmf_building_map_tools building_map_generator gazebo /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/clinic/clinic.building.yaml /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/clinic/clinic.world /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/clinic/models
DOWNLOADING MODELS WITH COMMAND: ros2 run rmf_building_map_tools building_map_model_downloader /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/clinic/clinic.building.yaml
BUILDING WORLDFILE WITH COMMAND: ros2 run rmf_building_map_tools building_map_generator gazebo /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/hotel/hotel.building.yaml /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/hotel/hotel.world /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/hotel/models
DOWNLOADING MODELS WITH COMMAND: ros2 run rmf_building_map_tools building_map_model_downloader /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/hotel/hotel.building.yaml
BUILDING WORLDFILE WITH COMMAND: ros2 run rmf_building_map_tools building_map_generator gazebo /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/office/office.building.yaml /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/office/office.world /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/office/models
DOWNLOADING MODELS WITH COMMAND: ros2 run rmf_building_map_tools building_map_model_downloader /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/office/office.building.yaml
BUILDING WORLDFILE WITH COMMAND: ros2 run rmf_building_map_tools building_map_generator gazebo /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/triple_H/triple_H.building.yaml /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/triple_H/triple_H.world /home/harunkurtdev/rmf_ws/build/rmf_demos_maps/maps/triple_H/models
DOWNLOADING MODELS WITH COMMAND: ros2 run rmf_building_map_tools building_map_model_downloader /home/harunkurtdev/rmf_ws/src/rmf_demos/rmf_demos_maps/maps/triple_H/triple_H.building.yaml
Package 'rmf_building_map_tools' not found
Package 'rmf_building_map_tools' not found
Package 'rmf_building_map_tools' not found
Package 'rmf_building_map_tools' not found
Package 'rmf_building_map_tools' not found
Package 'rmf_building_map_tools' not found
Package 'rmf_building_map_tools' not found
gmake[2]: *** [CMakeFiles/generate_clinic_crowdsim.dir/build.make:77: maps/clinic/clinic.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:411: CMakeFiles/generate_clinic_crowdsim.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
Package 'rmf_building_map_tools' not found
gmake[2]: *** [CMakeFiles/generate_airport_terminal_crowdsim_ign.dir/build.make:77: maps/airport_terminal_ign/airport_terminal.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:203: CMakeFiles/generate_airport_terminal_crowdsim_ign.dir/all] Error 2
Package 'rmf_building_map_tools' not found
gmake[2]: *** [CMakeFiles/generate_airport_terminal_crowdsim.dir/build.make:77: maps/airport_terminal/airport_terminal.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:177: CMakeFiles/generate_airport_terminal_crowdsim.dir/all] Error 2
gmake[2]: *** [CMakeFiles/generate_battle_royale_nav_graphs.dir/build.make:73: maps/battle_royale/nav_graphs/phony] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:307: CMakeFiles/generate_battle_royale_nav_graphs.dir/all] Error 2
gmake[2]: *** [CMakeFiles/generate_clinic_nav_graphs.dir/build.make:73: maps/clinic/nav_graphs/phony] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:463: CMakeFiles/generate_clinic_nav_graphs.dir/all] Error 2
gmake[2]: *** [CMakeFiles/generate_battle_royale_crowdsim_ign.dir/build.make:77: maps/battle_royale_ign/battle_royale.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:281: CMakeFiles/generate_battle_royale_crowdsim_ign.dir/all] Error 2
gmake[2]: *** [CMakeFiles/generate_battle_royale_crowdsim.dir/build.make:77: maps/battle_royale/battle_royale.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:255: CMakeFiles/generate_battle_royale_crowdsim.dir/all] Error 2
Package 'rmf_building_map_tools' not found
Package 'rmf_building_map_tools' not found
Package 'rmf_building_map_tools' not found
gmake[2]: *** [CMakeFiles/generate_airport_terminal_nav_graphs.dir/build.make:73: maps/airport_terminal/nav_graphs/phony] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:229: CMakeFiles/generate_airport_terminal_nav_graphs.dir/all] Error 2
gmake[2]: *** [CMakeFiles/generate_campus_nav_graphs.dir/build.make:73: maps/campus/nav_graphs/phony] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:385: CMakeFiles/generate_campus_nav_graphs.dir/all] Error 2
Package 'rmf_building_map_tools' not found
Package 'rmf_building_map_tools' not found
Package 'rmf_building_map_tools' not found
gmake[2]: *** [CMakeFiles/generate_campus_crowdsim.dir/build.make:77: maps/campus/campus.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:333: CMakeFiles/generate_campus_crowdsim.dir/all] Error 2
gmake[2]: *** [CMakeFiles/generate_office_crowdsim.dir/build.make:77: maps/office/office.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:567: CMakeFiles/generate_office_crowdsim.dir/all] Error 2
gmake[2]: *** [CMakeFiles/generate_hotel_nav_graphs.dir/build.make:73: maps/hotel/nav_graphs/phony] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:541: CMakeFiles/generate_hotel_nav_graphs.dir/all] Error 2
Package 'rmf_building_map_tools' not found
gmake[2]: *** [CMakeFiles/generate_clinic_crowdsim_ign.dir/build.make:77: maps/clinic_ign/clinic.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:437: CMakeFiles/generate_clinic_crowdsim_ign.dir/all] Error 2
gmake[2]: *** [CMakeFiles/generate_hotel_crowdsim.dir/build.make:77: maps/hotel/hotel.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:489: CMakeFiles/generate_hotel_crowdsim.dir/all] Error 2
gmake[2]: *** [CMakeFiles/generate_hotel_crowdsim_ign.dir/build.make:77: maps/hotel_ign/hotel.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:515: CMakeFiles/generate_hotel_crowdsim_ign.dir/all] Error 2
gmake[2]: *** [CMakeFiles/generate_campus_crowdsim_ign.dir/build.make:77: maps/campus_ign/campus.world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:359: CMakeFiles/generate_campus_crowdsim_ign.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< rmf_demos_maps [1.37s, exited with code 2]
Aborted  <<< rmf_demos_bridges [1.55s]           
Aborted  <<< rmf_demos_tasks [1.56s]
Aborted  <<< rmf_demos_fleet_adapter [1.57s]
Aborted  <<< rmf_demos_panel [0.52s]                      

Summary: 2 packages finished [1.84s]
  1 package failed: rmf_demos_maps
  4 packages aborted: rmf_demos_bridges rmf_demos_fleet_adapter rmf_demos_panel rmf_demos_tasks
  1 package had stderr output: rmf_demos_maps
  3 packages not processed
harunkurtdev@harunkurtdev:~/rmf_ws$ 
```
I use same code but not work me
```bash
mkdir ~/rmf_ws/src -p
cd ~/rmf_ws/src
git clone https://github.com/open-rmf/rmf_demos.git -b 2.0.3
cd ~/rmf_ws
colcon build
````

**Comment by harunkurtdev** [comment]
can you try this for solve
```bash
sudo apt install ros-humble-rmf-building-map-tools
```

**Comment by chou-dan** [comment]
You can modify line 146 of floor.py to  (in  rmf_ws/src/rmf/rmf_traffic_editor/rmf_building_map_tools/building_map/floor.py)


for item in geom.geoms:

No Thanks,haha.
